#!/bin/bash

# This bash script uses the current working directory to create a simple
# script to run the lpilWeb command anywhere in a user's
# workspace.

##########################################################################

recordcmdScript=$(pwd)/.venv/bin/lpilWeb

cat << CMD_SCRIPT > $HOME/.local/bin/lpilWeb
#!/bin/sh

# This shell script was created by the pygments-tools tool
#       './scripts/installEditableLpilWebCommand'
# script.

exec $recordcmdScript \$@
CMD_SCRIPT

chmod a+x $HOME/.local/bin/lpilWeb

##########################################################################

echo ""
echo "Editable lpilWeb command has been created"
echo ""
