#!/bin/bash

# This bash script pulls the current contents of the Gebry and LPiL
# PlasTeX plugins to the corresponding Python packages install in .venv

rm -rf .venv/lib/python3.11/site-packages/plasTeX
cp -R \
  ../plastex-test/plasTeX \
  .venv/lib/python3.11/site-packages/plasTeX

rm -rf .venv/lib/python3.11/site-packages/plastex_gerby_plugin
cp -R \
  ../plastex-gerby-plugin/plastex_gerby_plugin \
  .venv/lib/python3.11/site-packages/plastex_gerby_plugin

rm -rf .venv/lib/python3.11/site-packages/plastex_lpil_plugin
cp -R \
  ../plastex-lpil-plugin/plastex_lpil_plugin \
  .venv/lib/python3.11/site-packages/plastex_lpil_plugin

